name: Run Python Crawler

on:
  schedule:
    - cron: "0 */24 * * *" # 24마다 시간 실행
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          cd crawler
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          cd crawler
          python crawler.py # 이곳에 실제 파이썬 파일명을 적어주세요.

      - name: Commit and push changes
        if: steps.changed-files.outputs.files_changed == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ..
          git commit -m "Update building_infos.json"
          git push https://github.com/ShinYoung-hwan/SKKU-Buildings.git HEAD:main
